package com.thang.chargeops.station.exception.violation;

public enum StationPricingViolation {
    MIN_BOOKING_DURATION_INVALID,
    MIN_BOOKING_DURATION_90_NOT_SUPPORTED,
    BASE_PRICE_INVALID,
    OPERATING_WEEK_INVALID,
    OPEN_24_HOURS_PERIOD_NOT_ALLOWED,
    CLOSED_DAY_TIME_PRESENT,
    OPEN_DAY_TIME_REQUIRED,
    OPERATING_WINDOW_AMBIGUOUS,
    TOU_RULES_REQUIRED,
    TOU_NAME_REQUIRED,
    TOU_NAME_DUPLICATED,
    TOU_WINDOW_INVALID,
    TOU_RATE_INVALID,
    TOU_RULES_OVERLAP,
    CONFIGURATION_CONFLICT,
    SCHEDULE_CONFLICT_WITH_BOOKINGS
}
