package com.thang.chargeops.exception.errorcode;

import com.thang.chargeops.exception.errormessage.ErrorMessage;
import com.thang.chargeops.exception.errormessage.StationErrorMessage;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum StationErrorCode implements BaseErrorCode {

    STATION_NOT_FOUND(
            HttpStatus.NOT_FOUND, "STATION_001", StationErrorMessage.STATION_NOT_FOUND),
    STATION_ACCESS_DENIED(
            HttpStatus.FORBIDDEN, "STATION_002", StationErrorMessage.STATION_ACCESS_DENIED),
    INVALID_STATUS_TRANSITION(
            HttpStatus.CONFLICT, "STATION_003", StationErrorMessage.INVALID_STATUS_TRANSITION),
    CHARGE_POINT_NOT_FOUND(
            HttpStatus.NOT_FOUND, "STATION_007", StationErrorMessage.CHARGE_POINT_NOT_FOUND),
    CHARGE_POINT_CODE_ALREADY_EXISTS(
            HttpStatus.CONFLICT, "STATION_008", StationErrorMessage.CHARGE_POINT_CODE_ALREADY_EXISTS),
    CONNECTOR_NOT_FOUND(
            HttpStatus.NOT_FOUND, "STATION_009", StationErrorMessage.CONNECTOR_NOT_FOUND),
    CONNECTOR_CODE_ALREADY_EXISTS(
            HttpStatus.CONFLICT, "STATION_010", StationErrorMessage.CONNECTOR_CODE_ALREADY_EXISTS),
    STATION_SUSPENSION_REASON_REQUIRED(
            HttpStatus.BAD_REQUEST, "STATION_012", StationErrorMessage.STATION_SUSPENSION_REASON_REQUIRED),
    STATION_REACTIVATION_REASON_REQUIRED(
            HttpStatus.BAD_REQUEST, "STATION_013", StationErrorMessage.STATION_REACTIVATION_REASON_REQUIRED),
    INVALID_CHECK_IN_CHALLENGE(
            HttpStatus.BAD_REQUEST, "STATION_014", StationErrorMessage.INVALID_CHECK_IN_CHALLENGE),
    CONNECTOR_POWER_EXCEEDS_MAX_POWER(
            HttpStatus.BAD_REQUEST, "STATION_015", StationErrorMessage.CONNECTOR_POWER_EXCEEDS_MAX_POWER),
    CONNECTOR_POWER_RANGE_INVALID(
            HttpStatus.BAD_REQUEST, "STATION_016", StationErrorMessage.CONNECTOR_POWER_RANGE_INVALID),
    CHARGE_POINT_MAX_POWER_RANGE_INVALID(
            HttpStatus.BAD_REQUEST, "STATION_017", StationErrorMessage.CHARGE_POINT_MAX_POWER_RANGE_INVALID),
    CONNECTOR_TYPE_MISMATCH(
            HttpStatus.BAD_REQUEST, "STATION_018", StationErrorMessage.CONNECTOR_TYPE_MISMATCH),
    CHARGE_POINT_CODE_REQUIRED(
            HttpStatus.BAD_REQUEST, "STATION_019", StationErrorMessage.CHARGE_POINT_CODE_REQUIRED),
    CONNECTOR_CODE_REQUIRED(
            HttpStatus.BAD_REQUEST, "STATION_020", StationErrorMessage.CONNECTOR_CODE_REQUIRED),
    CONNECTOR_HAS_ACTIVE_BOOKINGS(
            HttpStatus.CONFLICT, "STATION_021", StationErrorMessage.CONNECTOR_HAS_ACTIVE_BOOKINGS),
    CHARGE_POINT_HAS_ACTIVE_BOOKINGS(
            HttpStatus.CONFLICT, "STATION_022", StationErrorMessage.CHARGE_POINT_HAS_ACTIVE_BOOKINGS),
    CHARGE_POINT_REQUIRES_CONNECTOR(
            HttpStatus.BAD_REQUEST, "STATION_023", StationErrorMessage.CHARGE_POINT_REQUIRES_CONNECTOR),
    INVALID_CHARGE_POINT_PROVISIONING_TRANSITION(
            HttpStatus.CONFLICT, "STATION_024", StationErrorMessage.INVALID_CHARGE_POINT_PROVISIONING_TRANSITION),
    CHARGE_POINT_SUSPENDED(
            HttpStatus.CONFLICT, "STATION_025", StationErrorMessage.CHARGE_POINT_SUSPENDED),
    CONNECTOR_RUNTIME_STATUS_SYSTEM_MANAGED(
            HttpStatus.CONFLICT, "STATION_026", StationErrorMessage.CONNECTOR_RUNTIME_STATUS_SYSTEM_MANAGED),
    STATION_NOT_ELIGIBLE_FOR_PROVISIONING(
            HttpStatus.CONFLICT, "STATION_027", StationErrorMessage.STATION_NOT_ELIGIBLE_FOR_PROVISIONING),
    CHARGE_POINT_STATUS_REASON_REQUIRED(
            HttpStatus.BAD_REQUEST, "STATION_028", StationErrorMessage.CHARGE_POINT_STATUS_REASON_REQUIRED),
    CONNECTOR_STATUS_REASON_REQUIRED(
            HttpStatus.BAD_REQUEST, "STATION_029", StationErrorMessage.CONNECTOR_STATUS_REASON_REQUIRED),
    CHARGE_POINT_OPERATIONAL_STATUS_REQUIRED(
            HttpStatus.BAD_REQUEST, "STATION_031", StationErrorMessage.CHARGE_POINT_OPERATIONAL_STATUS_REQUIRED),
    CONNECTOR_RUNTIME_STATUS_REQUIRED(
            HttpStatus.BAD_REQUEST, "STATION_032", StationErrorMessage.CONNECTOR_RUNTIME_STATUS_REQUIRED),
    CONNECTOR_HARDWARE_LOCKED(
            HttpStatus.CONFLICT, "STATION_033", StationErrorMessage.CONNECTOR_HARDWARE_LOCKED),
    CONNECTOR_NOT_AVAILABLE_FOR_CHECK_IN(
            HttpStatus.CONFLICT, "STATION_034", StationErrorMessage.CONNECTOR_NOT_AVAILABLE_FOR_CHECK_IN),
    CHARGE_POINT_CONNECTOR_COUNT_MISMATCH(
            HttpStatus.CONFLICT, "STATION_035", StationErrorMessage.CHARGE_POINT_CONNECTOR_COUNT_MISMATCH),
    CHARGE_POINT_DRAFT_DELETE_ONLY(
            HttpStatus.CONFLICT, "STATION_036", StationErrorMessage.CHARGE_POINT_DRAFT_DELETE_ONLY),
    CONNECTOR_DRAFT_DELETE_ONLY(
            HttpStatus.CONFLICT, "STATION_037", StationErrorMessage.CONNECTOR_DRAFT_DELETE_ONLY),
    STATION_NOT_ELIGIBLE_FOR_NEW_BUSINESS(
            HttpStatus.CONFLICT, "STATION_038", StationErrorMessage.STATION_NOT_ELIGIBLE_FOR_NEW_BUSINESS),
    CONNECTOR_NOT_BOOKABLE(
            HttpStatus.CONFLICT, "STATION_039", StationErrorMessage.CONNECTOR_NOT_BOOKABLE),
    PRICING_MIN_BOOKING_DURATION_INVALID(
            HttpStatus.BAD_REQUEST, "STATION_040", StationErrorMessage.PRICING_MIN_BOOKING_DURATION_INVALID),
    PRICING_MIN_BOOKING_DURATION_90_NOT_SUPPORTED(
            HttpStatus.BAD_REQUEST, "STATION_057", StationErrorMessage.PRICING_MIN_BOOKING_DURATION_90_NOT_SUPPORTED),
    PRICING_OPERATING_WEEK_INVALID(
            HttpStatus.BAD_REQUEST, "STATION_041", StationErrorMessage.PRICING_OPERATING_WEEK_INVALID),
    PRICING_CLOSED_DAY_TIME_PRESENT(
            HttpStatus.BAD_REQUEST, "STATION_042", StationErrorMessage.PRICING_CLOSED_DAY_TIME_PRESENT),
    PRICING_OPEN_DAY_TIME_REQUIRED(
            HttpStatus.BAD_REQUEST, "STATION_043", StationErrorMessage.PRICING_OPEN_DAY_TIME_REQUIRED),
    PRICING_OPERATING_WINDOW_AMBIGUOUS(
            HttpStatus.BAD_REQUEST, "STATION_044", StationErrorMessage.PRICING_OPERATING_WINDOW_AMBIGUOUS),
    PRICING_TOU_RULES_REQUIRED(
            HttpStatus.BAD_REQUEST, "STATION_045", StationErrorMessage.PRICING_TOU_RULES_REQUIRED),
    PRICING_TOU_NAME_DUPLICATED(
            HttpStatus.BAD_REQUEST, "STATION_046", StationErrorMessage.PRICING_TOU_NAME_DUPLICATED),
    PRICING_TOU_WINDOW_INVALID(
            HttpStatus.BAD_REQUEST, "STATION_047", StationErrorMessage.PRICING_TOU_WINDOW_INVALID),
    PRICING_TOU_RATE_INVALID(
            HttpStatus.BAD_REQUEST, "STATION_048", StationErrorMessage.PRICING_TOU_RATE_INVALID),
    PRICING_TOU_RULES_OVERLAP(
            HttpStatus.BAD_REQUEST, "STATION_049", StationErrorMessage.PRICING_TOU_RULES_OVERLAP),
    PRICING_BASE_PRICE_INVALID(
            HttpStatus.BAD_REQUEST, "STATION_050", StationErrorMessage.PRICING_BASE_PRICE_INVALID),
    PRICING_TOU_NAME_REQUIRED(
            HttpStatus.BAD_REQUEST, "STATION_051", StationErrorMessage.PRICING_TOU_NAME_REQUIRED),
    PRICING_OPEN_24_HOURS_PERIOD_NOT_ALLOWED(
            HttpStatus.BAD_REQUEST, "STATION_052", StationErrorMessage.PRICING_OPEN_24_HOURS_PERIOD_NOT_ALLOWED),
    PRICING_CONFIGURATION_CONFLICT(
            HttpStatus.CONFLICT, "STATION_053", StationErrorMessage.PRICING_CONFIGURATION_CONFLICT),
    STATION_OPERATING_SCHEDULE_REQUIRED(
            HttpStatus.CONFLICT, "STATION_054", StationErrorMessage.STATION_OPERATING_SCHEDULE_REQUIRED),
    STATION_OPERATIONAL_STATUS_REQUIRED(
            HttpStatus.BAD_REQUEST, "STATION_055", StationErrorMessage.STATION_OPERATIONAL_STATUS_REQUIRED),
    STATION_OPERATIONAL_STATUS_REASON_REQUIRED(
            HttpStatus.BAD_REQUEST, "STATION_056", StationErrorMessage.STATION_OPERATIONAL_STATUS_REASON_REQUIRED);

    private final HttpStatus httpStatus;
    private final String code;
    private final ErrorMessage.Template template;

    @Override
    public String getMessageKey() {
        return template.key();
    }

    @Override
    public String getMessage() {
        return template.defaultMessage();
    }
}
